### DISCUSSION TITLE
Can I put the slider on the left like with direction: rtl?

### DISCUSSION THREAD

**Discussion by ghost** [idiotWu/smooth-scrollbar#374] [Q&A]
Hello, how can I put the scroll on the left side of the page, direction: rtl does not affect the scroll, flex-direction: row-reverse too...

**Comment by sadeghbarati** [comment]
Add this css

```css
.scrollbar-track-y {
    right: auto !important;
    left: 0;
}
```
