### DISCUSSION TITLE
An easier way to customize the scrollbars' appearance

### DISCUSSION THREAD

**Discussion by blitzve0** [idiotWu/smooth-scrollbar#399] [Ideas]
Currently if we want to change the styling of the scroll bar thumb and tracks we have to overwrite the default styling from node modules. If basics settings like color transparency tracks color width padding etc could be set through config would be awesome

**Comment by dolphin-wood** [comment]
Maybe we can use CSS variables to do this? For example:

```css
:root {
  --scrollbar-track-width: 8px;
}

/* overwrite */
.your-scrollbar {
  --scrollbar-track-width: 10px;
}
```
