### DISCUSSION TITLE
Horizontal Scroll even after Disable X-Axis Scrolling

### DISCUSSION THREAD

**Discussion by blitzve0** [idiotWu/smooth-scrollbar#480] [Q&A] [answered]
https://user-images.githubusercontent.com/67477131/171929609-cdce99fa-e567-408e-8621-3e6c7e1b7ee8.mp4

Hi, I am using a plugin to disable X-axis horizontal scrolling totally, but sometimes accidentally when I hold and drag from the right edge, the site starts horizontally dragging. You can check the video and can try it out also here https://haspr.in/

This is the Plugin
```
import Scrollbar from 'smooth-scrollbar'

class DisableScroll extends Scrollbar.ScrollbarPlugin {
  static pluginName = 'DisableScroll'

  transformDelta(delta, fromEvent) {
    delta['x'] = 0

    return delta
  }
}

DisableScroll.pluginName = 'DisableScroll'
export default DisableScroll

```

**Comment by dolphin-wood** [comment, marked as answer]
Oh, that's because we forget to make the scrolling `delta` from `select` events transformable 🤦‍♂️. That's surely a bug, but I think we can get rid of the horizontal scrollbars with several lines of CSS, and you won't need a plugin anymore:

```css
.layout {
    /* height: 100vh; <- not sure why you wrote this but it seems safe to delete it */
    background: #fff;
    overflow: hidden; /* add this */
}
```

----

Edit: you also need to recalculate the floating contact button's position to avoid overflow: `bottom = scrollbar.limit.y - scrollbar.offset.y`. Here is a helper function for fixed elements: https://codesandbox.io/s/smooth-scrollbar-fixed-element-ki0syo?file=/src/fixed-element.ts

**Reply by blitzve0** [reply]
Hi I tried this CSS Trick, and its working but unfortunately it's breaking a lot of functionality, like the menu and page transitions suddenly became super laggy and a lot of gsap animations are not working due to this, is there a way to remove that select event scrolling ?

**Reply by dolphin-wood** [reply]
`user-select: none` will disable select events though. But I'd suggest you fix the horizontal overflow caused by `.pin-spacer` first.

**Comment by sadeghbarati** [comment]
@blitzve0 

- Best practice for smooth-scrollbar is don't initialize `Scrollbar` on the body
- Create another wrapper and init `Scrollbar` on it
- You may face some issues on `Safari` if you init `Scrollbar` on the body
- If you init `Scrollbar` on body add these styles
```css
html,
body {
    overflow: hidden;
    position: relative;
    height: 100%;
}

/*
if safari
*/
body.lock-scroll {
    position: fixed;
    inset: 0; /* https://caniuse.com/?search=inset */
    top: 0;
    left: 0;
}
``` 
- Take a look at [GSAP ScrollTrigger + smooth-scrollbar](https://codepen.io/GreenSock/pen/oNLqgBm) example
- Check [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock/) code for safari
-  Check https://idiotwu.github.io/smooth-scrollbar/ 
```css
html, body {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    color: #555;
    font-size: 16px;
    font-family: 'Hiragino Sans GB', 'Microsoft YaHei', 'WenQuanYi Micro Hei', sans-serif;
}
```

position fixed on both html, body can be used to solve overflow problems, but It may disrupt the gsap ScrollTrigger function without set ScrollTrigger default `scroller` element

```js
const scroller = document.querySelector("#main-scrollbar")
ScrollTrigger.defaults({ scroller  });
```
