### DISCUSSION TITLE
SyntaxError: Cannot use import statement outside a module

### DISCUSSION THREAD

**Discussion by Kishan7054** [idiotWu/smooth-scrollbar#503] [Q&A]
When i m importing overscroll plugin and use it it thows SyntaxError: Cannot use import statement outside a module

Can someone help me out this 
![Screenshot 2022-11-01 at 1 17 29 PM](https://user-images.githubusercontent.com/77719762/199184446-975f1407-05d3-4193-8766-333c541ea3fc.png)

**Comment by sadeghbarati** [comment]
Please share [minimal repro](https://antfu.me/posts/why-reproductions-are-required) cause we don't know what tool you using


- What is your `nextjs` version?
- Application is `server-side` or `client-side`?

**Comment by Kishan7054** [comment]
I m using nextjs 13 and smooth scrollbar

**Reply by sadeghbarati** [reply]
> Turbopack is currently in **alpha**. It is not yet ready for production use. We appreciate your support and feedback as we work to make it ready for everyone.

maybe Turbopack can't bundle sources correctly

I'll test `smooth-scrollbar` with nextjs 13 later, I will tell you the result

**Reply by Kishan7054** [reply]
bt it was also giving same error on next 12.3.1

**Reply by sadeghbarati** [reply]
can you share your repository?

I think it's `server-side` related.

**Reply by sadeghbarati** [reply]
https://beta.nextjs.org/docs/rendering/server-and-client-components#convention

for `nextjs` **13** add "use client" directive in the first line of your `smooth-scrollbar` component.

```ts
'use client';

import { FC, ReactNode, useEffect, useRef } from 'react'
.
.
.
```

**Reply by Kishan7054** [reply]
Still getting the same issue

**Reply by Kishan7054** [reply]
Sorry its client project I cant share it

**Reply by sadeghbarati** [reply]
Works fine for me

`app/smoothScrollbar.tsx`:
```ts
'use client';

import { useEffect, useRef } from "react"
import Scrollbar from 'smooth-scrollbar'
import OverscrollPlugin from 'smooth-scrollbar/plugins/overscroll'

Scrollbar.use(OverscrollPlugin)

export default function SmoothScrollbar({children}: { children: React.ReactNode}) {

  const smoothScrollbarDOM = useRef<HTMLDivElement | null>(null)

  useEffect(() => {
  
    Scrollbar.init(smoothScrollbarDOM.current!, {
      damping: 0.1,
      alwaysShowTracks: false,
      plugins: {
        overscroll: {
          effect: navigator.userAgent.match(/Android/) ? 'glow' : 'bounce',
        }
      }
    })
    
  }, [])

  return (
    <div className="smooth-scrollbar" ref={smoothScrollbarDOM}>{children}</div>
  )
}
```

`app/global.css`:

```css
html,
body {
  padding: 0;
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
    Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
  overflow: hidden !important;
}

a {
  color: inherit;
  text-decoration: none;
}

* {
  box-sizing: border-box;
}

@media (prefers-color-scheme: dark) {
  html {
    color-scheme: dark;
  }
  body {
    color: white;
    background: black;
  }
}

.smooth-scrollbar {
  height: 100vh;
}
```

`app/layout.tsx`:

```ts
import './globals.css'
import SmoothScrollbar from './smoothScrollbar'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <SmoothScrollbar>
          {children}
        </SmoothScrollbar>
      </body>
    </html>
  )
}
```
