### DISCUSSION TITLE
Stop scroll on x axis

### DISCUSSION THREAD

**Discussion by TravisDevLife** [idiotWu/smooth-scrollbar#511] [Q&A] [answered]
Hey guys, 

Just need some help on figuring out how to disable the scrolling on the X-Axis without the NPM install. Currently just using the plain js file and importing through unpkg.com. Any help would be nice!

Thanks!

**Comment by sadeghbarati** [comment]
Hi check this https://github.com/idiotWu/smooth-scrollbar/issues/481#issuecomment-1206183918




```js
window.myScrollbar = Scrollbar.init(document.getElementById('#scrollbar'))

const setMomentum = myScrollbar.prototype.setMomentum;

myScrollbar.prototype.setMomentum = function(x, y) {
    setMomentum.call(this, 0, y);
}
```


```css
html {
  scroll-behavior: initial;
}

html, body {
  height: 100%;
}

body 
  position: relative;
  overflow: hidden;
}

#scrollbar {
  width: 100%;
  height: 100vh;
  height: -webkit-fill-available;
}
```
