### ISSUE TITLE
Enable/Disable custom scrollbar appearance

### ISSUE THREAD

**Issue by HectorLS** [idiotWu/smooth-scrollbar#133]
- Version of smooth-scrollbar:   "smooth-scrollbar": "^8.2.5"

Hello,
I have noticed that now the scrollbar has his own design across all platforms (Chrome, Safari, Moz, IE) 👏  👏 

But lets say that i wish the originals ( even if they are uglies and different ), how can reset this ❓ 
Thanks id advance.

**Comment by idiotWu** [comment]
Try [`Scrollbar.detachStyle()`](https://github.com/idiotWu/smooth-scrollbar/blob/develop/docs/api.md#scrollbardetachstyle) static method :)

**Comment by HectorLS** [comment]
Great thank you so much

**Comment by HectorLS** [comment]
This method is not available on smooth-scrollbar": "^7.3.1",  right ?   i got undefined

**Comment by idiotWu** [comment]
Right. You can simply exclude css files to remove default styles.

**Comment by HectorLS** [comment]
> Right. You can simply exclude css files to remove default styles.

But by doing that i'm seeing both scrollers, a native/useless one, and the new one.

**Comment by HectorLS** [comment]
You mean like style the scrollbar like the old ones ? 
Its just because of a client request... no comments, i love the one that you provide but he wants the old style

**Comment by idiotWu** [comment]
Emmm...then I guess it may be better to use native scrollbars in your case.

**Comment by HectorLS** [comment]
In case someone need it, 
this do the trick, and you can also add the arrows using :before & :after

```scss
html.windows-scrollbar {
  body {
    .scrollbar-track.scrollbar-track-y {
      opacity: 1;
      background-color: #f1f1f1;
      width: 16px;

      .scrollbar-thumb.scrollbar-thumb-y {
        border-radius: 0px;
        background-color: rgb(193, 193, 192);
        width: 12px;
        left: 2px;
      }
    }
  }
}
```
