### ISSUE TITLE
Q: How to show scrollbar for a while after init?

### ISSUE THREAD

**Issue by netoper** [idiotWu/smooth-scrollbar#146]
Thank you for this amazing scrollbar!
I have question. All working great but when content is loaded, scrollbar not show. 
For first view i must move the wheel on the mouse. How to show scrollbar for a moment after init? Or show scrollbar when mouse is hovered or moving over scrolling element will be helpfull.

**Comment by idiotWu** [comment]
Call `scrollbar.update()` after content is loaded.

**Comment by netoper** [comment]
`scrollbar.update()` is attached to mouseenter event but not work.
[https://jsbin.com/navogunupe/edit?html,js,console,output](https://jsbin.com/navogunupe/edit?html,js,console,output)

**Comment by idiotWu** [comment]
If you meant the appearance, try the following css:

```css
@keyframes fadeOut {
  0%, 90% {
    opacity: 1;
  }
  
  100% {
    opacity: 0;
  }
}

.scrollbar-track {
  animation: fadeOut 3s;
}
```

Demo: https://jsbin.com/bapihib/1/edit?html,css,output

**Comment by netoper** [comment]
No, i do not mean appearance. I mean something like when you move mouse over the element, scrollbar is show and after a while it will disappear. Then when you use mouse scroll, scrollbar show again.
[https://codepen.io/haykou/pen/qbqBYM](https://codepen.io/haykou/pen/qbqBYM)

**Comment by idiotWu** [comment]
Try:

```css
@keyframes fade-out {
  0%, 90% {
    opacity: 1;
  }
  
  100% {
    opacity: 0;
  }
}

[data-scrollbar]:hover .scrollbar-track {
  animation: fade-out 3s;
}
```
