### ISSUE TITLE
Google Print Issue

### ISSUE THREAD

**Issue by coolteam573** [idiotWu/smooth-scrollbar#216]
After implementing the smooth-scrollbar on the website, Goggle Chrome default Print is not able to print whole web page. It is just printing the displayed area. Please have a look on the following URL and try to print page in Google Chrome

https://idiotwu.github.io/smooth-scrollbar/

**Comment by idiotWu** [comment]
You can use CSS media query to solve this issue:

```css
@media print {
  [data-scrollbar] { 
    overflow: auto !important;
    width: auto !important;
    height: auto !important;
    /* add other rules if needed */
  }
}

```
