### ISSUE TITLE
scrollbar not working with chromium (no errors)

### ISSUE THREAD

**Issue by ChazyTheBest** [idiotWu/smooth-scrollbar#54]
I got this beautiful plugin working with firefox but when I use chromium to go to my website the scroll is not working (the default scrollbar is hidden and the plugin is doing nothing).

I have a subdomain where I manually hide the scrollbar (`html, body { overflow: hidden }`) and I enable it in `<main>` and there it is working for both browsers.

Including the plugin normally inside the `<head>` element:

``` html
<link type="text/css" rel="stylesheet" media="all" href="<?= $static; ?>css/smooth-scrollbar.css" />
<script type="text/javascript" src="<?= $static; ?>js/smooth-scrollbar.js"></script>
```

```css
html, body { width: 100%; height: 100% }
main { width: 1170px; }
```

```javascript
Scrollbar.init(document.getElementsByTagName('body')[0], options);
```

The above is working fine in firefox, but for some reason, is not for chromium (the first one I tried).

Now, for my subdomain:

```css
html, body { overflow: hidden; width: 100%; height: 100vh }
main { overflow: auto; width: calc(100% - 200px); height: calc(100vh - 95px) }
```

```javascript
Scrollbar.init(document.getElementsByTagName('main')[0], options);
```

The above is working fine in both browsers. So my question is: Am I doing something wrong or is it a bug in the plugin?

Thanks! I really love this plugin!
